### ISSUE TITLE
"空白" 作者修正

### ISSUE THREAD

**Issue by Sam5440** [Sam5440/Genshin_Impact_Teleport#39]

**Comment by Sam5440** [comment]
<img width="752" alt="image" src="https://user-images.githubusercontent.com/47051833/219951581-a26f0eaa-3695-474f-a190-e22d4d03ac10.png">

**Comment by Sam5440** [comment]
[3.4.zip](https://github.com/Sam5440/Genshin_Impact_Teleport/files/10776999/3.4.zip)

**Comment by Drich3614** [comment]
#40 solved
