### ISSUE TITLE
missed 1 geoculus

### ISSUE THREAD

**Issue by covidjoiner** [Sam5440/Genshin_Impact_Teleport#41]
1 geoculus is missed. here is 131:

`{"description":"","name":"0131 - Geoculus","position":[839.3775634765625,543.0599975585938,1427.8603515625]}`

**Comment by Sam5440** [comment]
OK, thank you very much for your contribution. I will be adding him in the future.

**Comment by ShinaKaria** [comment]
auto generate have all the oculus before 3.4
